security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
          chain:
            providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
          main:
                      pattern: ^/
                      form_login:
                          provider: fos_userbundle
                          csrf_provider: form.csrf_provider
                          login_path: /login
                          check_path: /login_check
                      oauth:
                          resource_owners:
                              facebook:           "/login/check-facebook"
                          login_path:        /login
                          failure_path:      /login

                          oauth_user_provider:
                              service: hwio_user_provider
                      logout:       true
                      anonymous:    true

          login:
              pattern:  ^/login$
              security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/addProduct, role: [ROLE_USER]}